services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - app_network

  redis:
    image: redis:7
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume: 